version: "3.9"

services:
  nestjs-backend:
    build: .
    container_name: nestjs-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pearson1234
      DB_DATABASE: pearson_db
    restart: unless-stopped
    # Uncomment below if you want hot reload during dev (also add volumes)
    # volumes:
    #   - ./:/app
    # command: ["pnpm", "run", "start:dev"]
