services:
  backend:
    build: .
    container_name: pearson-backend
    ports:
      - '5000:5000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .develop.env
    environment:
      NODE_ENV: production
      MIGRATION_MODE: "true"
    restart: unless-stopped
    volumes:
      - ./.develop.env:/app/.env:ro
