services:
  backend:
    build: .
    container_name: pearson-backend
    ports:
      - '5000:5000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      NODE_ENV: production
    restart: unless-stopped
